easy_admin:
    site_name: 'Site perso de Matthieu'
    user:
        display_name: true
    design:
        menu:
            - { entity: User, icon: 'user' }
            - Project
            - { entity: Logo, icon: 'file-image' }
            - { entity: Image, icon: 'images' }
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - username
            form:
                fields:
                    - username
                    - roles
        Project:
            class: App\Entity\Project
            list:
                fields:
                    - title
                    - description
                    - link
                    - { property: 'image', type: 'file', base_path: '%app.path.project_images%' }
                    - { property: 'logos', type: 'array' }
            form:
                fields:
                    - title
                    - description
                    - link
                    - updatedAt
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'logos', type: 'entity', type_options: { class: 'App\Entity\Logo', by_reference: false } }
        Logo:
            class: App\Entity\Logo
            list:
                fields:
                    - title
                    - { property: image, type: 'file', base_path: '%app.path.project_images%' }
                    - updatedAt
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image' }
                    - updatedAt
        Image:
            class: App\Entity\Image
            list:
                fields:
                    - title
                    - { property: image, type: 'file', base_path: '%app.path.project_images%' }
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image' }
                    - updatedAt