easy_admin:
    site_name: 'Site perso de Matthieu'
    user:
        display_name: true
    entities:
        User:
            class: App\Entity\User
            icon: 'user'
            form:
                fields:
                    - username
                    - roles
        Projects:
            class: App\Entity\Project
            list:
                fields:
                    - title
                    - description
                    - link
                    - { property: 'image', type: 'file', base_path: '%app.path.project_images%' }
                    - { property: 'logos', type: 'array' }
            form:
                fields:
                    - title
                    - description
                    - link
                    - updatedAt
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'logos', type: 'entity', type_options: { class: 'App\Entity\Logo', by_reference: false } }
        Logo:
            class: App\Entity\Logo
            list:
                fields:
                    - title
                    - { property: image, type: 'file', base_path: '%app.path.project_images%' }
                    - updatedAt
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image' }
                    - updatedAt
        Image:
            class: App\Entity\Image
            list:
                fields:
                    - title
                    - { property: image, type: 'file', base_path: '%app.path.project_images%' }
            form:
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image' }
                    - updatedAt