easy_admin:
    site_name: 'Site perso de Matthieu'
    user:
        display_name: true
    entities:
        User:
            class: App\Entity\User
            icon: 'user'
            form:
                fields:
                    - username
                    - roles
        Projects:
            class: App\Entity\Project
            list:
                fields:
                    - title
                    - description
                    - link
                    - { property: image, type: 'file', base_path: '%app.path.project_images%' }
            show:
                fields:
                    - title
                    - description
                    - link
                    - { property: image, type: 'file', base_path: '%app.path.project_images%' }
            form:
                fields:
                    - title
                    - description
                    - link
                    - updatedAt
                    - { property: 'imageFile', type: 'vich_image' }
        Logo:
            class: App\Entity\Logo