easy_admin:
    site_name: 'Site perso de Matthieu'
    user:
        display_name: true
    entities:
        User:
            class: App\Entity\User
            icon: 'user'
        Projects:
            class: App\Entity\Project
        Logo:
            class: App\Entity\Logo