twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'theme/fields.html.twig'
    globals:
        project_collection: '@App\Application\Templating\Helper\ProjectHelper'
        captcha: '%env(GOOGLE_RECAPTCHA_SITE_KEY))%'