# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.path.project_images: /uploads/images

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $google_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
            $google_secret_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'
            $uploadDir: 'uploads/images'
            $sendGrid: '%env(MAILER_PASSWORD)%'
            $contactEmail: '%env(CONTACT_EMAIL)%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\ProjectImageListener:
        tags:
            - { name: doctrine.orm.entity_listener, event: post }
